# Blog settings
permalink: /blog/:title

name: react-boilerplate
description: A slightly opinionated setup for ReactJS
demo_url: dist
google_verification: null
twitter_username: mikechabot_
github_username:  mikechabot
email: mike.chabot@live.com
baseurl: "/"
url: "http://localhost:4000/"

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
